content:
        title: Resume | Zenahr
        greetingText: Greeting Text
        resumeText: This is where your resume text goes
        firstName: Your First Name
        lastName: Your Last Name
        socialIntroText: Here are some places on the internet you can reach me and find some of my work
        closingStatement:  See ya.
socials:
        github: https://www.github.com/Zenahr
        linkedIn: https://www.linkedin.com/in/zenahr-barzani
        email: dev@zenahr.com
styling:
        mainCssPath: ../src/css/main.css
        extendedCssPath: ../src/css/extended.css

js: 